### ISSUE TITLE
[Bug] woke process crashing repeatedly on codebase

### ISSUE THREAD

**Issue by jmhickman** [Ackee-Blockchain/tools-for-solidity-vscode#40] opened 2023-02-02 16:38 UTC
Extension version: 1.4.0

Codebase with issue: https://github.com/code-423n4/2023-01-popcorn

Setup commands: 
* `git clone --recurse-submodules https://github.com/code-423n4/2023-01-popcorn.git`
* `cd` into directory
* `forge install && yarn install`
* `forge build` to test that project compiles

Symptom: When compiling the codebase after issuing the "Import Foundry Remappings" command, this crash appears repeatedly in the log:
```bash
[Error - 4:09:42 PM] Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/server.py", line 259, in _task_done_callback
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 178, in run
    await self.__compilation_loop()
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 852, in __compilation_loop
    await self.__compile(self.__discovered_files)
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 731, in __compile
    path = cu.source_unit_name_to_path(PurePath(source_unit_name))
  File "/usr/local/lib/python3.10/dist-packages/woke/compile/compilation_unit.py", line 53, in source_unit_name_to_path
    return self.__unit_graph.nodes[source_unit_name]["path"]
  File "/usr/local/lib/python3.10/dist-packages/networkx/classes/reportviews.py", line 194, in __getitem__
    return self._nodes[n]
KeyError: PurePosixPath('node_modules/openzeppelin-upgradeable/interfaces/IERC4626Upgradeable.sol')
```

In an attempt to bypass this issue, I deleted the entire repo, set it up again but didn't run the "Import Foundry Remappings" command. Instead, I manually edited the files in the `src`  directory to point to the correct paths. This seemed to go well, until I got to the file `src/interfaces/vault/IERC4626.sol`. Upon fixing its import, I get the following repeatedly.

```bash
[Error - 4:24:36 PM] Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/server.py", line 259, in _task_done_callback
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 178, in run
    await self.__compilation_loop()
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 852, in __compilation_loop
    await self.__compile(self.__discovered_files)
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 775, in __compile
    self.__ir_reference_resolver.run_post_process_callbacks(
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/reference_resolver.py", line 96, in run_post_process_callbacks
    callback(callback_params)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/meta/import_directive.py", line 152, in _post_process
    assert referenced_declaration is not None
AssertionError
```

I narrowed the crashes down to this particular file, so you don't need to re-path everything. Simply changing the import 

```solidity
import { IERC20Upgradeable as IERC20 } from "openzeppelin-contracts-upgradeable/token/ERC20/IERC20Upgradeable.sol";
```
to

```solidity
import { IERC20Upgradeable as IERC20 } from "../../../node_modules/openzeppelin-upgradeable/token/ERC20/IERC20Upgradeable.sol";
```
is sufficient to cause the crash

**Comment by jmhickman** [comment] 2023-02-02 16:50
Interestingly, `src/vault/adapter/yearn/IYearn.sol` has the exact same import, and when corrected it doesn't cause any crashes.

**Comment by michprev** [comment] 2023-02-02 20:22
@jmhickman thank you for your bug report.

The problem is that the file `test/vault/integration/abstract/PropertyTest.prop.sol` imports `IERC20` which is a symbol alias created in `src/interfaces/vault/IERC4626.sol`:
```solidity
import { IERC20Upgradeable as IERC20 } from "openzeppelin-contracts-upgradeable/token/ERC20/IERC20Upgradeable.sol";
```

Because we do imported symbol resolving manually (there was a bug in the `solc` compiler) and we were not counting on this scenario (a symbol alias imported from another file), this causes an exception. It will be fixed in the next version of Woke (and Tools for Solidity).

As a temporal workaround, you can import `IERC20Upgradeable` instead of `IERC20`.

**Comment by jmhickman** [comment] 2023-02-02 23:16
Thanks for getting back to me!

Are you sure that's the only issue? If I delete the entire test directory (I don't absolutely require it for what I'm doing), the issue persists.

**Comment by michprev** [comment] 2023-02-07 19:55
The new version of Woke and Tools for Solidity should be working fine with the repository. Can you please give it a try?

**Comment by jmhickman** [comment] 2023-02-07 20:04
Can confirm this is fixed.

Thanks for getting the fix merged so quickly!

**Closed** 2023-02-07 20:08 UTC
